/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tours: Tour;
    pages: Page;
    blogs: Blog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tours: ToursSelect<false> | ToursSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Jairo is admin. Areli, Lizet and Ricardo are editors and can edit all fields.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * One document per market. Unique key is market + slug, not slug alone.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: number;
  market: 'en' | 'es' | 'pt';
  slug: string;
  /**
   * SEO / browser title
   */
  title: string;
  /**
   * Visible page heading — this is the 2-minute edit
   */
  h1: string;
  /**
   * Public from-price in USD. 0 = request quote.
   */
  priceFrom?: number | null;
  currency?: 'USD' | null;
  duration?: string | null;
  difficulty?: string | null;
  summary?: string | null;
  /**
   * Public URL or /images/... path. Media uploads come later (Vercel Blob).
   */
  heroImage?: string | null;
  gallery?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
  };
  itinerary?:
    | {
        day: number;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  excluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  relatedTourSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  categories?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Parte igual del catálogo. Cualquier editor puede reasignar.
   */
  assignee?: ('areli' | 'jairo' | 'lizet' | 'ricardo') | null;
  /**
   * HTML y código libre, como Drupal Full HTML. El equipo SEO puede pegar markup aquí; no está limitado.
   */
  customHtml?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  market: 'en' | 'es' | 'pt';
  slug: string;
  /**
   * Canonical path inside the market, e.g. /packages/
   */
  path: string;
  pageType?: ('home' | 'hub' | 'static' | 'destination') | null;
  title: string;
  h1?: string | null;
  heroHeadline?: string | null;
  heroSubtitle?: string | null;
  heroEmotionalLine?: string | null;
  heroImage?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
  };
  sections?:
    | {
        heading?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * HTML y código libre, como Drupal Full HTML. El equipo SEO puede pegar markup aquí; no está limitado.
   */
  bodyHtml?: string | null;
  childLinks?:
    | {
        path: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  tourSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Parte igual del catálogo. Cualquier editor puede reasignar.
   */
  assignee?: ('areli' | 'jairo' | 'lizet' | 'ricardo') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  market: 'en' | 'es' | 'pt';
  slug: string;
  title: string;
  h1?: string | null;
  heroImage?: string | null;
  intro?: string | null;
  category?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    canonical?: string | null;
  };
  sections?:
    | {
        heading?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * HTML y código libre, como Drupal Full HTML. El equipo SEO puede pegar markup aquí; no está limitado.
   */
  bodyHtml?: string | null;
  relatedTourSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  modifiedAt?: string | null;
  /**
   * Parte igual del catálogo. Cualquier editor puede reasignar.
   */
  assignee?: ('areli' | 'jairo' | 'lizet' | 'ricardo') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tours';
        value: number | Tour;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  market?: T;
  slug?: T;
  title?: T;
  h1?: T;
  priceFrom?: T;
  currency?: T;
  duration?: T;
  difficulty?: T;
  summary?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
      };
  itinerary?:
    | T
    | {
        day?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  relatedTourSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  categories?:
    | T
    | {
        name?: T;
        id?: T;
      };
  assignee?: T;
  customHtml?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  market?: T;
  slug?: T;
  path?: T;
  pageType?: T;
  title?: T;
  h1?: T;
  heroHeadline?: T;
  heroSubtitle?: T;
  heroEmotionalLine?: T;
  heroImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  bodyHtml?: T;
  childLinks?:
    | T
    | {
        path?: T;
        label?: T;
        id?: T;
      };
  tourSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  assignee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  market?: T;
  slug?: T;
  title?: T;
  h1?: T;
  heroImage?: T;
  intro?: T;
  category?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  bodyHtml?: T;
  relatedTourSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  publishedAt?: T;
  modifiedAt?: T;
  assignee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}